Repository arpit456jain/CodingEasy, pull requests merged in 2021-12, with the labels that each got.

#36 Added python course
  Python/Basic/Basic.css
  Python/Basic/Basic.html
  Python/Conditions/condition.css
  Python/Conditions/condition.html
  Python/DataTypes/datatypes.css
  Python/DataTypes/datatypes.html
  Python/File Handling/file.css
  Python/File Handling/file.html
  Python/Functions/function.css
  Python/Functions/function.html
  Python/Loop/loop.css
  Python/Loop/loop.html
  Python/Operator/operator.css
  Python/Operator/operator.html
  Python/RegEx/regex.css
  Python/RegEx/regex.html
  Python/python.css
  Python/python.html
  index.html
Labels: swoc'22, hard

#37 Added Contributor and Admin in README.md
  README.md
Labels: swoc'22, beginner

#39 Updated Readme.md file for UI enhancement
  README.md
Labels: swoc'22, beginner

#40 Added SWOC LOGO
  README.md
Labels: swoc'22, beginner

#44 Improved README.md
  README.md
Labels: swoc'22, beginner

#57 Replaced Front end Partner with Coding Easy in whole project - issue55
  Features/features.html
  Html/Basic/Basic.html
  Html/Images/images.html
  Html/Links/link.html
  Html/Lists/list.html
  Html/Style/style.html
  Html/Table/table.html
  Html/html.html
  Pricing/pricing.html
  Python/Basic/Basic.html
  Python/Conditions/condition.html
  Python/DataTypes/datatypes.html
  Python/File Handling/file.html
  Python/Functions/function.html
  Python/Loop/loop.html
  Python/python.html
  bootstrap/bootstrap.html
  css/allign/allign.html
  css/basic/basic.html
  css/color/color.html
  css/css.html
  css/font/font.html
  css/functions/functions.html
  css/properties/properties.html
  index.html
  javascr/datatypes/datatypes.html
  javascr/events/events.html
  javascr/functions/functions.html
  javascr/javascr.html
  javascr/jsclasses/jsclasses.html
  javascr/jsconditions/jsconditions.html
  javascr/jserrors/jserrors.html
  javascr/jsmath/jsmath.html
  javascr/jsnumbers/jsnumbers.html
  javascr/operators/operators.html
  javascr/string/string.html
  javascr/syntax/syntax.html
Labels: swoc'22, easy

#50 Added Common CSS File
  Html/Basic/Basic.html
  Html/Images/images.html
  Html/Links/link.html
  Html/Lists/list.html
  Html/Style/style.html
  Html/Table/table.html
  Html/html.html
  Pricing/pricing.html
  bootstrap/bootstrap.html
  common.css
  css/allign/allign.html
  css/basic/basic.css
  css/basic/basic.html
  css/color/color.html
  css/css.html
  css/font/font.html
  css/functions/functions.html
  css/properties/properties.html
Labels: swoc'22, medium
