Repository arpit456jain/CodingEasy, pull requests merged in 2022-03, with the labels that each got.

#144 docs: Added Code of conduct
  CODE_OF_CONDUCT.md
Labels: Level1

#174 Update features html
  templates/home/Features/features.html
  templates/home/base.html
Labels: Level1

#178 Add new jQuery Course part1
  home/urls.py
  home/views.py
  static/css/common.css
  static/css/jQuery/jQuery.css
  static/img/Thumbs.db
  static/img/jQuery.png
  static/img/jQueryDimensions.gif
  templates/home/base.html
  templates/home/index.html
  templates/home/jQuery/Attributes/attributes.html
  templates/home/jQuery/ManipulatingCSS/ManipulatingCSS.html
  templates/home/jQuery/ManipulatingCSS/jQueryCss.html
  templates/home/jQuery/ManipulatingCSS/jQueryDimensions.html
  templates/home/jQuery/Overview/Overview.html
  templates/home/jQuery/Overview/selectors.html
  templates/home/jQuery/jQuery.html
Labels: Level3

#182 The last Part of jQuery course
  home/views.py
  static/css/jQuery/jQuery.css
  templates/home/jQuery/Attributes/attributes.html
  templates/home/jQuery/Effects/effects.html
  templates/home/jQuery/Events/events.html
  templates/home/jQuery/ManipulatingDOM/ManipulatingDOM.html
  templates/home/jQuery/jQuery.html
Labels: Level3

#185 Reorder step of 'How to Make a Pull Request?'
  README.md
Labels: Level1

#186 Broken Links Fixed
  README.md
Labels: Level1

#201 [ADDED FEATURE] User Authentication System- Signin/Signup
  home/decorators.py
  home/forms.py
  home/urls.py
  home/views.py
  templates/home/Login/login.html
  templates/includes/navbar.html
Labels: Level3

#209 Added missing favicon
  CodingEasy/urls.py
  static/img/CodingEasy.png
  static/img/coding easy.png
  static/img/favicon.ico
  templates/home/Login/login.html
  templates/home/base.html
Labels: changes requested
