Repository arpit456jain/CodingEasy, pull requests merged in 2022-04, with the labels that each got.

#230 Loops added
  CodingEasy/views.py
  home/views.py
  static/img/loops.png
  templates/home/CPP/Loops/loops.html
  templates/home/CPP/cpp.html
Labels: GSSoC22, Level2

#238 Changes in Mentor Section
  README.md
Labels: GSSoC22, Level0

#235 Adding Git course
  CodingEasy/views.py
  home/urls.py
  home/views.py
  static/img/git_github.png
  templates/home/Git_GitHub/git.html
  templates/home/index.html
Labels: GSSoC22, Level2, changes requested

#239 YouTube Video Embedded
  templates/home/Git_GitHub/git.html
Labels: Feature, GSSoC22, Level2

#237 Code editor
  home/urls.py
  home/views.py
  templates/home/Editor/editor.html
  templates/home/Html/html.html
  templates/includes/navbar.html
Labels: urgent, Feature, GSSoC22, Level3, changes requested

#254 Added video tutorials on topic: Git and Github (Length > 5 minutes for both videos)
  video tutorials.xlsx
  video.tutorials.xlsx
Labels: Level2

#255 Added 3 videos of which 2 videos length > 5 min in ML.txt
  ML.txt
Labels: Level3
