Repository arpit456jain/CodingEasy, pull requests merged in 2022-01, with the labels that each got.

#73 Added Content in 4 Topics of PY
  Python/Basic/Basic.html
  Python/DataTypes/datatypes.html
  Python/Functions/function.html
  Python/Operator/operator.html
Labels: swoc'22, medium

#96 fixes issue#51
  .github/ISSUE_TEMPLATE/coding-easy-issue-template.md
  .github/Pr-Template.md
Labels: swoc'22, beginner

#99 Added Colors to Cpp page
  static/css/cpp/cpp.css
  templates/CPP/cpp.html
Labels: swoc'22, easy

#108 implement a download csv feature in admin panel for downloading the data as csv file
  CodingEasy/settings.py
  DashBoard/admin.py
  DashBoard/models.py
  requirements.txt
Labels: hard

#112 Added new course Git & GitHub
  templates/Git_GitHub/git.html
Labels: medium
