Repository arpit456jain/CodingEasy, pull requests merged in 2022-05, with the labels that each got.

#262 added 2 css videos of more than 5 min each
  Video tutorials/CSS.xlsx
Labels: Level2

#268 A separate page for listing our templates and downloading them #234
  home/urls.py
  home/views.py
  templates/home/listtemplates/css/csstemplates.html
  templates/home/listtemplates/frontend/frontendtemplates.html
  templates/home/listtemplates/js/jstemplates.html
  templates/home/listtemplates/listtemplates.html
  templates/includes/navbar.html
Labels: GSSoC22, Level3

#274 Added 2 videos of length more than 5 min
  Video tutorials/ML.xlsx
Labels: GSSoC22

#276 templates of css and js not showing #269
  home/views.py
  static/json/csstemp.json
  static/json/frontend.json
  static/json/jstemp.json
  templates/home/listtemplates/css/csstemplates.html
  templates/home/listtemplates/frontend/frontendtemplates.html
  templates/home/listtemplates/js/jstemplates.html
Labels: GSSoC22, Level3

#278 2 videos (length>5min) on demo of linear regression and different commands
  Video tutorials/ML.xlsx
Labels: GSSoC22, Level3

#280 Added Html video
  Video tutorials/HTML.xlsx
Labels: GSSoC22

#279 Added details is JSON File
  static/json/content_writers.json
  static/json/mentors.json
  static/json/top_contributors.json
  static/json/video_creators.json
  static/json/web_developers.json
  templates/home/team/our_team.html
Labels: GSSoC22

#282 Updated Linear_Regression.html
  templates/home/ML/Linear_Regression/Linear_Regression.html
Labels: GSSoC22, Level1

#283 Adding the right routes for the C course and some other changes in the description
  blog/urls.py
  blog/views.py
  home/decorators.py
  home/urls.py
  home/views.py
  media/Thumbs.db
  media/posts_pic/Bug_mJOxyIv.png
  media/posts_pic/account-disabled.gif
  media/posts_pic/girl2.png
  media/profile_pics/girl-wave_DLGfX7M.gif
  static/img/Thumbs.db
  static/img/c_lang.png
  templates/blog/base.html
  templates/blog/blog-categories.html
  templates/blog/blog-navbar.html
  templates/blog/categories.html
  templates/blog/category.html
  templates/blog/category_detail.html
  templates/blog/home.html
  templates/blog/post_search_result.html
  templates/home/C/arrays/arrays.html
  templates/home/C/c.html
  templates/home/C/descision-making/descision.html
  templates/home/C/functions/functions.html
  templates/home/C/keywords/keywords.html
  templates/home/C/loop-types/loops.html
  templates/home/C/numbers/numbers.html
  templates/home/C/operators/operators.html
  templates/home/C/strings/strings.html
  templates/home/CPP/abstraction/abstraction.html
  templates/home/CPP/arrays/arrays.html
  templates/home/CPP/class/class.html
  templates/home/CPP/cpp.html
  templates/home/CPP/descition/descition.html
  templates/home/CPP/dynamic/dynamic.html
  templates/home/CPP/encapsulation/encapsulation.html
  templates/home/CPP/except/except.html
  templates/home/CPP/functions/functions.html
  templates/home/CPP/inheritance/inheritance.html
  templates/home/CPP/interfaces/interfaces.html
  templates/home/CPP/namespaces/namespaces.html
  templates/home/CPP/numbers/numbers.html
  templates/home/CPP/overloading/overloading.html
  templates/home/CPP/pointers/pointers.html
  templates/home/CPP/polymorphism/polymorphism.html
  templates/home/CPP/strings/strings.html
  templates/home/CPP/templates/templates.html
  templates/home/index.html
  templates/includes/navbar.html
Labels: GSSoC22, Level3

#275 Updating search form and search result page
  templates/blog/blog-navbar.html
  templates/blog/post_search_result.html
  templates/includes/navbar.html
Labels: GSSoC22

#289 Added 3 Videos(1 more than 7 min length) on creating two different model and compare their rmse value
  Video tutorials/ML.xlsx
Labels: GSSoC22, Level3

#290 Updating users roles for our blog
  blog/urls.py
  blog/views.py
  home/views.py
  media/posts_pic/404-hexxa_0ZyCmQp.jpg
  media/posts_pic/7481.jpg
  media/posts_pic/7584.jpg
  media/posts_pic/Code_gift.gif
  media/posts_pic/account-disabled_c3qWkEw.gif
  media/posts_pic/background.jpg
  media/posts_pic/banner_3x1MYBs.png
  media/posts_pic/bird.png
  media/posts_pic/check_email_CtAKy5h.gif
  media/posts_pic/d.jpg
  media/posts_pic/we_are_here_bvvXNaD.png
  media/posts_pic/website_background_ga24eOp.jpg
  media/profile_pics/Hi.gif
  media/profile_pics/me_coding.gif
  media/profile_pics/octocat.png
  templates/blog/base.html
  templates/blog/blog-navbar.html
  templates/home/base.html
  templates/home/index.html
  templates/includes/messages.html
Labels: GSSoC22, Level3

#296 Fixed bug in the team page
  templates/home/Python/Conditions/condition.html
  templates/home/team/our_team.html
Labels: GSSoC22, Level1

#293 Added 4 videos on Demo of Linear REgression using python
  Video tutorials/ML.xlsx
Labels: GSSoC22, Level3

#300 Embedded Python IDE
  templates/home/Python/Conditions/condition.html
  templates/home/Python/File Handling/file.html
  templates/home/Python/Functions/function.html
  templates/home/Python/Loop/loop.html
  templates/home/base.html
Labels: GSSoC22, Level2

#305 Added 4 videos related to creating two different model and compared them.
  Video tutorials/ML.xlsx
Labels: GSSoC22, Level2

#307 Embed IDE in JS/CPP/Python files
  templates/home/CPP/Data_Types/data_types.html
  templates/home/CPP/Loops/loops.html
  templates/home/CPP/Operators/operators.html
  templates/home/Python/DataTypes/datatypes.html
  templates/home/Python/RegEx/regex.html
  templates/home/javascr/functions/functions.html
  templates/home/javascr/jsclasses/jsclasses.html
  templates/home/javascr/jsconditions/jsconditions.html
  templates/home/javascr/jserrors/jserrors.html
  templates/home/javascr/jsmath/jsmath.html
  templates/home/javascr/jsnumbers/jsnumbers.html
  templates/home/javascr/objects/objects.html
  templates/home/javascr/operators/operators.html
  templates/home/javascr/string/string.html
  templates/home/javascr/syntax/syntax.html
Labels: GSSoC22

#309 Added 2 Videos on Logistic Regression
  Video tutorials/ML.xlsx
Labels: GSSoC22, Level2

#304 Adding staff roles
  blog/templatetags/__init__.py
  blog/templatetags/has_group.py
  blog/views.py
  media/posts_pic/19787204_1323996111032620_530381105642120159_o.jpg
  media/posts_pic/5371.jpg
  media/posts_pic/6p3M08-tAVlfvEgrFTkrDOccuRRPzmAP9lZo.gif
  media/posts_pic/7481_XQvyeyA.jpg
  media/posts_pic/7486.jpg
  templates/blog/base.html
  templates/blog/blog-navbar.html
  templates/blog/category_detail.html
Labels: GSSoC22, Level2

#312 Fixed URL bug and embed IDE in C pages
  templates/home/C/Data_Types/data_types.html
  templates/home/C/Variable_Types/Variable_Types.html
  templates/home/C/arrays/arrays.html
  templates/home/C/c.html
  templates/home/C/descision-making/descision.html
  templates/home/C/functions/functions.html
  templates/home/C/loop-types/loops.html
  templates/home/C/operators/operators.html
  templates/home/C/strings/strings.html
Labels: GSSoC22

#315 Added 2 Videos on random forest
  Video tutorials/ML.xlsx
Labels: GSSoC22

#318 Added 3 videos on demo of random forest and introduction to naive bayes
  Video tutorials/ML.xlsx
Labels: GSSoC22, Level2

#321 Added 3 videos on demo of naive bayes and KNN
  Video tutorials/ML.xlsx
Labels: GSSoC22, Level3

#320 IDE in HTML page
  templates/home/Html/Basic/Basic.html
  templates/home/Html/Images/images.html
  templates/home/Html/Links/link.html
  templates/home/Html/Lists/list.html
  templates/home/Html/Style/style.html
  templates/home/Html/Table/table.html
Labels: GSSoC22

#323 Added 3 videos on KNN and K means clustering
  Video tutorials/ML.xlsx
Labels: GSSoC22

#324 Added video tutorials on topic: Git and Github (Length>5 min)
  Video tutorials/Git Github.xlsx
Labels: GSSoC22

#326 Documentation made right
  README.md
Labels: GSSoC22, Level0

#327 updated doc for data-types
  templates/home/CPP/Data_Types/data_types.html
Labels: GSSoC22, Level2

#328 added video of more than 15 mins on css
  Video tutorials/CSS (3).xlsx
  Video tutorials/CSS.xlsx
Labels: documentation, GSSoC22, Level1

#329 added 2 videos of more than 15 mins length on css
  Video tutorials/CSS (3).xlsx
  Video tutorials/CSS..xlsx
Labels: GSSoC22

#332 Addded 2 videos of 10 to 15 mins
  Video tutorials/CSS. (1).xlsx
  Video tutorials/CSS..xlsx
Labels: GSSoC22, Level3

#333 Added 2 videos on demo of KMC and introduction video SVM
  Video tutorials/ML.xlsx
Labels: GSSoC22

#334 added 2 videos of 10 to 16 mins on css
  Video tutorials/CSS. (1).xlsx
  Video tutorials/CSS1.xlsx
Labels: GSSoC22

#341 Added 2 videos on use cases of SVM and SVM kernels and it's implementation step.
  Video tutorials/ML.xlsx
Labels: GSSoC22, Level2

#338 added 3 videos of approx. 15 mins on css
  Video tutorials/CSS1 (1).xlsx
  Video tutorials/CSS1.xlsx
Labels: GSSoC22, Level3

#335 Sections, Documentation, Resourses for Git and Github
  CodingEasy/views.py
  home/urls.py
  home/views.py
  templates/home/Git_GitHub/advanced/advanced.html
  templates/home/Git_GitHub/basic/basic.html
  templates/home/Git_GitHub/git.html
  templates/home/Git_GitHub/intermediate/intermediate.html
Labels: GSSoC22, Level2

#342 Added 3 videos of 11 to 16 mins on topic css
  Video tutorials/CSS1 (1) (1).xlsx
  Video tutorials/CSS1 (1).xlsx
Labels: GSSoC22

#343 Added 2 videos on demo of svm
  Video tutorials/ML.xlsx
Labels: GSSoC22

#344 Added 2 videos on HCA
  Video tutorials/ML.xlsx
Labels: GSSoC22

#348 Added 2 videos on Measure distance between two clusters and AHC python implementation steps
  Video tutorials/ML.xlsx
Labels: GSSoC22

#346 Added 3 videos of 10 to 15 mins on topic css
  Video tutorials/CSS.xlsx
  Video tutorials/CSS1 (1) (1).xlsx
Labels: GSSoC22, Level3

#347 Added descison,functions &Numbers content in C++
  home/views.py
  templates/home/CPP/decision/decision.html
  templates/home/CPP/descition/descition.html
  templates/home/CPP/functions/functions.html
  templates/home/CPP/numbers/numbers.html
Labels: GSSoC22

#349 Added Content in arrays,pointers,strings in c++
  templates/home/CPP/arrays/arrays.html
  templates/home/CPP/pointers/pointers.html
  templates/home/CPP/strings/strings.html
Labels: GSSoC22, Level2

#350 Added 3 videos of 10 to 15 mins on css
  Video tutorials/CSS.xlsx
Labels: GSSoC22, Level3

#351 Added 2 videos on Demo of HCA na d adv /disadv of HCA
  Video tutorials/ML.xlsx
Labels: GSSoC22

#355 Added 2 videos on One hot encoding
  Video tutorials/ML.xlsx
Labels: GSSoC22, Level3

#353 added 3 videos of 10 to 15 mins on css
  Video tutorials/CSS (4).xlsx
  Video tutorials/CSS.xlsx
Labels: GSSoC22, Level2

#354 Updating our team page
  static/json/top_contributors.json
  static/json/web_developers.json
  templates/home/team/our_team.html
Labels: GSSoC22, Level1

#345 Quiz page
  home/models.py
  home/signals.py
  home/urls.py
  home/views.py
  static/json/quizCategory.json
  static/json/quizJSON/quizPython.json
  templates/includes/navbar.html
  templates/quiz/quizBootstrap.html
  templates/quiz/quizC.html
  templates/quiz/quizCpp.html
  templates/quiz/quizCss.html
  templates/quiz/quizDjango.html
  templates/quiz/quizHtml.html
  templates/quiz/quizJquery.html
  templates/quiz/quizJs.html
  templates/quiz/quizMl.html
  templates/quiz/quizPython.html
  templates/quiz/quizhome.html
  templates/quiz/result.html
Labels: GSSoC22, Level2

#356 Added 3 vidoes of 10 to 15 mins on css
  Video tutorials/CSS (4).xlsx
  Video tutorials/CSS.xlsx
Labels: GSSoC22

#357 Added 2 videos of 10 to 15 mins on css
  Video tutorials/CSS.xlsx
Labels: GSSoC22, Level2

#362 Added 2 videos of 10 to 15 mins on topic css
  Video tutorials/CSS.xlsx
Labels: GSSoC22

#368 Added 2 videos on topic css units and website layout
  Video tutorials/CSS.xlsx
Labels: GSSoC22

#365 Added 3 videos on One hot encoding and k fold cross validation
  Video tutorials/ML.xlsx
Labels: GSSoC22

#370 Added 2 videos on K fold cross validation
  Video tutorials/ML.xlsx
Labels: GSSoC22, Level3

#369 Added 2 videos on css specificity and css !important
  Video tutorials/CSS.xlsx
Labels: GSSoC22, Level3

#363 Added answers section in Quiz Result Page
  home/views.py
  templates/quiz/result.html
Labels: GSSoC22, Level1

#372 Added 2 videos on css Maths functions including calc(),max(),and min() functions
  Video tutorials/CSS.xlsx
Labels: GSSoC22

#375 added 2 videos of border-image and border-radius on css advance
  Video tutorials/CSS.xlsx
Labels: GSSoC22

#374 UI improvement in python module
  templates/home/ML/ML.html
  templates/home/Pricing/pricing.html
  templates/home/Python/Conditions/condition.html
  templates/home/Python/Exception/exception.html
  templates/home/Python/File Handling/file.html
  templates/home/Python/Functional_Programming/functional_programming.html
  templates/home/Python/Functions/function.html
  templates/home/Python/Loop/loop.html
  templates/home/Python/RegEx/regex.html
  templates/home/Python/Working_with_Strings/working_with_strings.html
  templates/includes/navbar.html
Labels: GSSoC22, Level3

#377 added 2 videos on background-property and clip property
  Video tutorials/CSS (4).xlsx
  Video tutorials/CSS.xlsx
Labels: GSSoC22, Level2

#380 Added 2 videos on demo of K fold cross validation
  Video tutorials/ML.xlsx
Labels: GSSoC22

#373 Improving the Cards of our website courses
  static/css/cards.css
  static/img/Thumbs.db
  static/json/top_contributors.json
  static/json/web_developers.json
  templates/home/base.html
  templates/home/index.html
Labels: GSSoC22, changes requested

#381 Added 2 videos of about 10 mins on topic css
  Video tutorials/CSS (4) (1).xlsx
  Video tutorials/CSS (4).xlsx
Labels: GSSoC22

#384 Added 2 videos on GridSearch
  Video tutorials/ML.xlsx
Labels: GSSoC22

#379 Added Content in arrays,numbers,strings in C
  templates/home/C/arrays/arrays.html
  templates/home/C/numbers/numbers.html
  templates/home/C/strings/strings.html
Labels: GSSoC22, Level1

#387 Added 2 videos of more than 10 mins on css including colors keywords and gradient topics
  Video tutorials/CSS (4) (1) (1).xlsx
  Video tutorials/CSS (4) (1).xlsx
Labels: GSSoC22

#382 Added content to remaining C++ topics
  templates/home/CPP/abstraction/abstraction.html
  templates/home/CPP/class/class.html
  templates/home/CPP/dynamic/dynamic.html
  templates/home/CPP/encapsulation/encapsulation.html
  templates/home/CPP/except/except.html
  templates/home/CPP/inheritance/inheritance.html
  templates/home/CPP/interfaces/interfaces.html
  templates/home/CPP/namespaces/namespaces.html
  templates/home/CPP/overloading/overloading.html
  templates/home/CPP/polymorphism/polymorphism.html
  templates/home/CPP/templates/templates.html
Labels: GSSoC22, Level3

#386 Adding all videos to the Git & GitHub course
  templates/home/Git_GitHub/advanced/advanced.html
  templates/home/Git_GitHub/basic/basic.html
  templates/home/Git_GitHub/intermediate/intermediate.html
Labels: GSSoC22, Level1

#393 Added Video solution on remove element
  Video tutorials/LEETCODE PROBLEM SOLUTION.txt
  Video tutorials/LEETCODE PROBLLEM SERIES.xlsx
Labels: GSSoC22

#396 Added video solution for Maximum subarray
  Video tutorials/LEETCODE PROBLEM SOLUTION.txt
  Video tutorials/LEETCODE PROBLLEM SERIES.xlsx
Labels: GSSoC22

#395 Added two video tutorials on an array
  Video tutorials by Tushar/Remove Duplicates from Sorted Array.txt
  Video tutorials by Tushar/Two sum.txt
Labels: GSSoC22, Level2

#394 Added 4 videos of 10 mins on topic css
  Video tutorials/CSS (4) (1) (1).xlsx
  Video tutorials/CSS.xlsx
Labels: GSSoC22, Level3

#392 Adding try me for modules and UI issues in bootstrap course #367
  templates/home/bootstrap/button/button.html
  templates/home/bootstrap/cards/cards.html
  templates/home/bootstrap/carousel/carousel.html
  templates/home/bootstrap/container/container.html
  templates/home/bootstrap/grid/grid.html
  templates/home/bootstrap/jumbotron/jumbotron.html
  templates/home/bootstrap/modal/modal.html
  templates/home/bootstrap/navbar/navbar.html
Labels: GSSoC22, Level3

#398 Adding 14 videos to CSS course
  home/views.py
  media/posts_pic/06_211025_CompanyEC_16x9__30fps__1080-1.gif
  media/posts_pic/1608981008842.jpg
  media/posts_pic/404-hexxa_lvtobUm.jpg
  media/posts_pic/5302_jARwsZm.jpg
  media/posts_pic/angle_brackets.gif
  media/posts_pic/cross.gif
  media/profile_pics/GitHub_sExm9rn.png
  media/profile_pics/banner.png
  media/profile_pics/code.gif
  templates/home/css/basic/basic.html
  templates/home/css/css.html
  templates/home/css/font-family/font-family.html
  templates/home/css/functions/functions.html
  templates/home/css/selectors/selectors.html
Labels: GSSoC22

#400 Adding new topics and edit old docs in CSS Course
  home/views.py
  templates/home/css/basic/basic.html
  templates/home/css/borders/borders.html
  templates/home/css/boxModel/boxModel.html
  templates/home/css/color/color.html
  templates/home/css/comments/comments.html
  templates/home/css/css.html
Labels: GSSoC22, Level3

#401 Added 4 videos on html topic
  Video tutorials/HTML (1).xlsx
  Video tutorials/HTML.xlsx
Labels: GSSoC22

#402 Added 2 video solutions of leetcode
  Video tutorials by Tushar/Length of Last Word.txt
  Video tutorials by Tushar/Palindrome Number.txt
Labels: GSSoC22

#403 Added solution video for merge sorted array
  Video tutorials/LEETCODE PROBLEM SOLUTION.txt
  Video tutorials/LEETCODE PROBLLEM SERIES.xlsx
Labels: GSSoC22, Level1

#404 Added two video tutorials of leetcode
  Video tutorials by Tushar/Add Digits.txt
  Video tutorials by Tushar/Reverse Integer.txt
Labels: GSSoC22

#405 Code editor added in Bootstrap
  templates/home/bootstrap/bootstrap.html
  templates/home/bootstrap/button/button.html
  templates/home/bootstrap/cards/cards.html
  templates/home/bootstrap/carousel/carousel.html
  templates/home/bootstrap/color/color.html
  templates/home/bootstrap/container/container.html
  templates/home/bootstrap/grid/grid.html
  templates/home/bootstrap/jumbotron/jumbotron.html
  templates/home/bootstrap/modal/modal.html
  templates/home/bootstrap/navbar/navbar.html
Labels: GSSoC22

#407 Added 4 videos on html topic
  Video tutorials/HTML (1).xlsx
  Video tutorials/HTML.xlsx
Labels: GSSoC22, Level2

#408 Added IDE in CPP files
  templates/home/CPP/Constants/Literals/Constants.html
  templates/home/CPP/Data_Types/data_types.html
  templates/home/CPP/Modifiers/modifiers.html
  templates/home/CPP/Operators/operators.html
  templates/home/CPP/Storage_Classes/storage_classes.html
  templates/home/CPP/abstraction/abstraction.html
  templates/home/CPP/arrays/arrays.html
  templates/home/CPP/class/class.html
  templates/home/CPP/decision/decision.html
  templates/home/CPP/dynamic/dynamic.html
  templates/home/CPP/encapsulation/encapsulation.html
  templates/home/CPP/except/except.html
  templates/home/CPP/functions/functions.html
  templates/home/CPP/inheritance/inheritance.html
  templates/home/CPP/interfaces/interfaces.html
  templates/home/CPP/namespaces/namespaces.html
  templates/home/CPP/numbers/numbers.html
  templates/home/CPP/overloading/overloading.html
  templates/home/CPP/pointers/pointers.html
  templates/home/CPP/polymorphism/polymorphism.html
  templates/home/CPP/strings/strings.html
Labels: GSSoC22, Level2

#409 Added two video tutorials of leetcode
  Video tutorials by Tushar/Remove Element.txt
  Video tutorials by Tushar/Single Number.txt
Labels: GSSoC22

#410 Added code editor in Cpp modules and fixed not rendering decision module
  home/views.py
  static/json/top_contributors.json
  templates/home/CPP/Constants/Literals/Constants.html
  templates/home/CPP/Operators/operators.html
  templates/home/CPP/Storage_Classes/storage_classes.html
  templates/home/CPP/Variable_Types/Variable_Types.html
  templates/home/CPP/abstraction/abstraction.html
  templates/home/CPP/cpp.html
  templates/home/CPP/decision/decision.html
  templates/home/CPP/except/except.html
  templates/home/CPP/overloading/overloading.html
  templates/home/CPP/polymorphism/polymorphism.html
  templates/home/CPP/templates/templates.html
Labels: GSSoC22

#413 Added 4 videos of html topic
  Video tutorials/HTML (3).xlsx
  Video tutorials/HTML.xlsx
Labels: GSSoC22

#417 Added 4 videos on html topic
  Video tutorials/HTML (3) (1).xlsx
  Video tutorials/HTML (3).xlsx
Labels: GSSoC22

#416 Added video solution on convert sorted array to binary search tree
  Video tutorials/LEETCODE PROBLEM SOLUTION.txt
  Video tutorials/LEETCODE PROBLLEM SERIES.xlsx
Labels: GSSoC22

#418 Added two video tutorials of leetcode
  Video tutorials by Tushar/Happy Number.txt
  Video tutorials by Tushar/Reverse Words in a String.txt
Labels: GSSoC22

#414 Added Quiz Pages in C/CPP/Js/Django Pages
  home/urls.py
  home/views.py
  static/json/quizCategory.json
  static/json/quizJSON/quizC.json
  static/json/quizJSON/quizCpp.json
  static/json/quizJSON/quizDjango.json
  static/json/quizJSON/quizJs.json
  templates/quiz/quizC.html
  templates/quiz/quizCpp.html
  templates/quiz/quizDjango.html
  templates/quiz/quizJs.html
Labels: GSSoC22, Level3

#415 Adding editors to the C course modules and keywords module added
  templates/home/C/Constants/Literals/Constants.html
  templates/home/C/Modifiers/modifiers.html
  templates/home/C/arrays/arrays.html
  templates/home/C/c.html
  templates/home/C/keywords/keywords.html
  templates/home/C/loop-types/loops.html
  templates/home/C/numbers/numbers.html
  templates/home/C/operators/operators.html
Labels: GSSoC22

#419 Added Two video tutorials of leetcode
  Video tutorials/LeetCode Problem Solutions/Find the difference.txt
  Video tutorials/LeetCode Problem Solutions/contains duplicate.txt
Labels: GSSoC22

#421 Added 4 vidoes on html topic
  Video tutorials/HTML (3) (1) (1).xlsx
  Video tutorials/HTML (3) (1).xlsx
Labels: GSSoC22

#422 Added video solution on Best Time To Buy And Sell Stock
  Video tutorials/LEETCODE PROBLEM SOLUTION.txt
  Video tutorials/LEETCODE PROBLLEM SERIES.xlsx
Labels: GSSoC22

#427 Adding 31 videos to ML Course
  templates/home/ML/Decision_Tree/Decision_Tree.html
  templates/home/ML/Gridsearch/Gridsearch.html
  templates/home/ML/Hierarchical Clustering/Hierarchical Clustering.html
  templates/home/ML/K-Fold Cross Validation/K-Fold Cross Validation.html
  templates/home/ML/K_Means_Clustering/K_Means_Clustering.html
  templates/home/ML/K_Nearest_Neighbors/K_Nearest_Neighbors.html
  templates/home/ML/Linear_Regression/Linear_Regression.html
  templates/home/ML/Logistic_Regression/Logistical_Regression.html
  templates/home/ML/ML.html
  templates/home/ML/Naive_Bayes/Naive_Bayes.html
  templates/home/ML/One Hot Encoding/One Hot Encoding.html
  templates/home/ML/Random_Forest/Random_Forest.html
  templates/home/ML/Support_Vector_Machines/Support_Vector_Machines.html
Labels: GSSoC22, Level3

#426 Adding 20 videos to ML Course in 5 topics and the main page of the Course
  templates/home/ML/Decision_Tree/Decision_Tree.html
  templates/home/ML/Linear_Regression/Linear_Regression.html
  templates/home/ML/Logistic_Regression/Logistical_Regression.html
  templates/home/ML/ML.html
  templates/home/ML/Random_Forest/Random_Forest.html
Labels: GSSoC22

#423 Added 4 videos on html topic
  Video tutorials/HTML (3) (1) (1).xlsx
Labels: GSSoC22, Level2

#424 Design Github Pages and Add missing videos
  templates/home/Git_GitHub/advanced/advanced.html
  templates/home/Git_GitHub/basic/basic.html
  templates/home/Git_GitHub/intermediate/intermediate.html
Labels: GSSoC22

#425 Added Two video tutorials of leetcode
  Video tutorials/LeetCode Problem Solutions/Power of two.txt
  Video tutorials/LeetCode Problem Solutions/Ugly number.txt
Labels: GSSoC22

#429 Added Two video tutorials of leetcode
  Video tutorials/LeetCode Problem Solutions/Majority Element.txt
  Video tutorials/LeetCode Problem Solutions/Valid Anagram.txt
Labels: GSSoC22

#431 Added video solution on Pascals triangle
  Video tutorials/LEETCODE PROBLEM SOLUTION.txt
  Video tutorials/LEETCODE PROBLLEM SERIES.xlsx
Labels: GSSoC22

#432 Improving the code indentation in the html course and fix some syntax error in some codes
  templates/home/Html/Basic/Basic.html
  templates/home/Html/Images/images.html
  templates/home/Html/Links/link.html
  templates/home/Html/Lists/list.html
  templates/home/Html/Style/style.html
  templates/home/Html/Table/table.html
  templates/home/Html/html.html
Labels: GSSoC22

#438 Added 4 videos on html topic
  Video tutorials/HTML (3) (1) (1).xlsx
Labels: GSSoC22

#437 Added two video tutorials of Leetcode
  Video Tutorials by Riya/Max Consecutive Ones.txt
  Video Tutorials by Riya/Subarray Sum Equals K.txt
Labels: GSSoC22, Level2

#436 Added Two video tutorials of leetcode
  Video tutorials/LeetCode Problem Solutions/Fibonacci number.txt
  Video tutorials/LeetCode Problem Solutions/Reverse String.txt
Labels: GSSoC22, Level2

#440 Added two video tutorials of youtube
  Video tutorials by Tushar/Valid Anagram.txt
  Video tutorials by Tushar/Valid Palindrome.txt
Labels: GSSoC22

#439 Added 4 videos on html topic
  Video tutorials/HTML (3) (1) (1).xlsx
Labels: GSSoC22

#445 added aadDigits leetcode Video Tutorial, added django database tutorial
  Video tutorials/Django Tutorials/databsae django tutorial.txt
  Video tutorials/LeetCode Problem Solutions/Add digits.txt
Labels: GSSoC22

#444 Added 3 video solution of Leetcode
  Video tutorials/LEETCODE PROBLEM SOLUTION.txt
  Video tutorials/LEETCODE PROBLLEM SERIES.xlsx
Labels: GSSoC22

#446 Adding 9 videos to the html course in 3 topics
  templates/home/Html/Lists/list.html
  templates/home/Html/Style/style.html
  templates/home/Html/Table/table.html
Labels: GSSoC22, Level1

#448 Added video solution to Leetcode Q287
  Video tutorials/LeetCode Problem Solutions/FindTheDuplicateNumber.cpp
Labels: GSSoC22

#449 Added 6 videos on html topic
  Video tutorials/HTML (3) (1) (1).xlsx
Labels: GSSoC22

#450 Added 2 video solution for leetcode
  Video tutorials/LEETCODE PROBLEM SOLUTION.txt
  Video tutorials/LEETCODE PROBLLEM SERIES.xlsx
Labels: GSSoC22

#455 Added 3 video solution of leetcode
  Video tutorials/LEETCODE PROBLEM SOLUTION.txt
  Video tutorials/LEETCODE PROBLLEM SERIES.xlsx
Labels: GSSoC22

#451 Adding 10 videos in the html videos in two topics
  media/posts_pic/404-hexxa_rl586tO.jpg
  media/posts_pic/5302_I3Ydnfg.jpg
  media/posts_pic/angle_brackets_aRnRvEg.gif
  media/posts_pic/bird_SvH5RbQ.png
  media/profile_pics/banner_SjMnK7G.png
  media/profile_pics/dive_ritzIOh.jpg
  media/profile_pics/girl-holding-tablet.png
  templates/home/Html/Images/images.html
  templates/home/Html/Style/style.html
Labels: GSSoC22, Level2

#452 Added 4 videos on HTML topic
  Video tutorials/HTML (3) (1) (1).xlsx
Labels: GSSoC22, Level2

#453 Adding code editors in python course
  templates/home/Python/Basic/Basic.html
  templates/home/Python/Exception/exception.html
  templates/home/Python/Functional_Programming/functional_programming.html
  templates/home/Python/OOP/oop.html
  templates/home/Python/Operator/operator.html
  templates/home/Python/Working_with_Strings/working_with_strings.html
  templates/home/Python/python.html
Labels: GSSoC22, Level2

#454 Added video solution for leetcode Q74
  Video tutorials/LeetCode Problem Solutions/SearchIn2DMatrix.cpp
Labels: GSSoC22, Level2

#456 Added Two video tutorials of leetcode
  Video tutorials/LeetCode Problem Solutions/Intersection of Two Arrays.txt
  Video tutorials/LeetCode Problem Solutions/Missing Number.txt
Labels: GSSoC22

#457 Added2 video solution for leetcode
  Video tutorials/LEETCODE PROBLEM SOLUTION.txt
  Video tutorials/LEETCODE PROBLLEM SERIES.xlsx
Labels: GSSoC22, Level2

#458 Added 3 video tutorials of leetcode
  Video tutorials/LeetCode Problem Solutions/Group Anagrams.txt
  Video tutorials/LeetCode Problem Solutions/Linked List Cycle.txt
  Video tutorials/LeetCode Problem Solutions/Plus one.txt
Labels: GSSoC22, Level3

#459 LeetCode Videos
  home/urls.py
  home/views.py
  templates/home/Leetcode/LeetCode.html
  templates/includes/navbar.html
Labels: GSSoC22, Level3

#460 Added 4 videos on HTML topic
  Video tutorials/HTML (3) (1) (1).xlsx
Labels: GSSoC22, Level2

#461 Adding LeetCode card in the home page and add it's link in the dropdown list of Courses
  static/img/Thumbs.db
  static/img/leetcode.jpg
  templates/home/index.html
  templates/includes/navbar.html
Labels: urgent, GSSoC22, Level2

#466 Added 6 videos on HTML topic
  Video tutorials/HTML (3) (1) (1).xlsx
Labels: GSSoC22

#467 Added 3 video tutorials of leetcode
  Video tutorials/LeetCode Problem Solutions/Check If String Is a Prefix of Array.txt
  Video tutorials/LeetCode Problem Solutions/Concatenation of Array.txt
  Video tutorials/LeetCode Problem Solutions/Sorting the Sentence.txt
Labels: GSSoC22

#464 Added 3 video tutorials of leetcode
  Video tutorials/LeetCode Problem Solutions/Check if the Sentence Is Pangram.txt
  Video tutorials/LeetCode Problem Solutions/How Many Numbers Are Smaller Than the Current Number.txt
  Video tutorials/LeetCode Problem Solutions/Truncate Sentence.txt
Labels: GSSoC22, Level3

#462 Added 3 video tutorials of leetcode
  Video tutorials/LeetCode Problem Solutions/Linked List Cycle II
  Video tutorials/LeetCode Problem Solutions/Middle of the Linked List.txt
  Video tutorials/LeetCode Problem Solutions/Unique Number of Occurrences.txt
Labels: GSSoC22, Level3

#468 Added 3 videos solution for leetcode
  Video tutorials/LEETCODE PROBLEM SOLUTION.txt
  Video tutorials/LEETCODE PROBLLEM SERIES.xlsx
Labels: GSSoC22

#463 Adding all the new HTML videos uploaded to YouTube
  templates/home/Html/Style/style.html
Labels: GSSoC22

#469 Making The main Navbar fixed to the top of the webpage and adding a side Navbar
  templates/home/base.html
  templates/home/index.html
  templates/includes/footer.html
  templates/includes/navbar.html
  templates/includes/side-navbar.html
Labels: GSSoC22

#471 Added 1 video solution for leetcode
  Video tutorials/LEETCODE PROBLEM SOLUTION.txt
  Video tutorials/LEETCODE PROBLLEM SERIES.xlsx
Labels: GSSoC22
